### PR TITLE
Added LittleFS and FatFS choice on drop-down

### PR DESCRIPTION
**Pull request by lorol**
If you ever want to have this hack to add LittleFS and FatFS choice to the original tool made only for SPIFFS ... please consider this PR

### CODE REVIEW

**Comment by lorol** [comment]
Added FatFS,, mk...fs binaries and modified Update lib to work with all three filesystems through serial port and ota.

**Comment by lbernstone** [comment]
This either needs to be merged, or forked into its own project, as there are a number of issues being reported that won't apply to @me-no-dev's version.

**Comment by lorol** [comment]
@lbernstone 
I really added stuff after that request to resolve my needs, and built it in a dummy way w/o any planned and tested approach by different hosts and so on. 
If you'd like to re-develop it in a proper way - please do it.
Especially FFat part - it is basically based on your idea and the counterpart mk binaries can be linked from original repositories.

**Review by lorol — COMMENTED** [review]
Added LittleFS and FFat choices as well as "erase all" choices to the original SPIFFS tool.

**Comment by lbernstone** [comment]
Can you separate out the bits that are absolutely needed to support the esp32s2 and submit those as a separate PR?  That is what really needs to make it back upstream.

**Comment by lorol** [comment]
@lbernstone 
In this case it is best to ask @zouffin the author of this addition to PR direct;y to upstream repository.
See here how the story started:
https://github.com/lorol/arduino-esp32fs-plugin/pull/2
And I do not have s2 device to test.

**Comment by lorol** [comment]
Agree with @lbernstone  for more conservative PR approach with fewer changes at a time, starting by most important ones.
Maybe later will PR again

**Pull request closed without merging**
